# TEST FILE
# Has only a few events, to check for major errors.
# 
# Change the default number of workers (in multi-threading mode) 
/run/numberOfThreads 1
#
# Initialize kernel
#/cuts/setLowEdge 1 eV
#/run/setCut 1 nm
/run/initialize
#
/control/verbose 2
/run/verbose 2
/event/verbose 2
/tracking/verbose 2
/analysis/verbose 1
/run/printProgress 1
#
/ChicagoGeom/deleteGeometry
/ChicagoGeom/setShield Pb

/analysis/setFileName /data/ncorso/Neutron_output/output/output_test/Neutron.root

/gps/pos/type Point
/gps/pos/centre 0 0 110 mm
#/gps/pos/centre 0 -6.614 -19.98 mm

/gps/particle neutron
/gps/energy 10 keV

/gps/ang/type iso
#/gps/ang/mintheta 0 deg
#/gps/ang/maxtheta 85 deg

/run/beamOn 3
