# Macro file for example Trit
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfThreads 30
#
# Initialize kernel
#/cuts/setLowEdge 1 eV
#/run/setCut 1 nm
/run/initialize
#
/control/verbose 2
/run/verbose 2
/event/verbose 2
/tracking/verbose 2
/run/printProgress 1
#/analysis/verbose 2
#
#/analysis/setFileName /data/ncorso/Compton_output/output/output_test/Compton_Co.root

/gps/pos/type Point
/gps/pos/centre 0 0 110 mm

#/gps/pos/centre 0 -6.614 12.4055 mm

/gps/particle ion
/gps/ion 27 57 0 0
/gps/energy 0 keV

/gps/ang/type iso
#/gps/ang/mintheta 0 rad
#/gps/ang/maxtheta 0.052 rad

/run/beamOn 3

# /analysis/setFileName /data/ncorso/Compton_output/output/output/Compton_Am.root
# /gps/pos/type Point
# /gps/pos/centre 0 0 110 mm
# /gps/particle ion
# /gps/ion 95 241 0 0
# /gps/energy 0 keV
# /gps/ang/type iso
# /run/beamOn 10000000
