# TEST FILE
# Has a sizable but not overwhelming number of events to check for low probability errors.
# 
# Change the default number of workers (in multi-threading mode) 
/run/numberOfThreads 1
#
# Initialize kernel
#/cuts/setLowEdge 1 eV
#/run/setCut 1 nm
/run/initialize
#
/control/verbose 0
/run/verbose 1
/event/verbose 0
/tracking/verbose 0
/run/printProgress 1
#/analysis/verbose 2
#
/analysis/setFileName /data/ncorso/Compton_output/output/output_test/Compton_Co.root

/gps/pos/type Point
#/gps/pos/centre 0 0 110 mm
/gps/pos/centre 0 -6.614 -19. mm

/gps/particle neutron
/gps/energy 10 keV

#/gps/ang/type focused
#/gps/ang/focuspoint 0 -6.614 12.4055 mm
/gps/ang/type iso
/gps/ang/mintheta 0 deg
/gps/ang/maxtheta 85 deg

/run/beamOn 10000000

# /analysis/setFileName /data/ncorso/Compton_output/output/output/Compton_Am.root
# /gps/pos/type Point
# /gps/pos/centre 0 0 -110 mm
# /gps/particle ion
# /gps/ion 95 241 0 0
# /gps/energy 0 keV
# /gps/ang/type iso
# /run/beamOn 10000000
